services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3010:3010'
        env_file:
            - .env
        restart: always
        volumes:
            - ./:/app
            - backend_node_modules:/app/node_modules
        depends_on:
            database:
                condition: service_healthy
        networks:
            - contributions_network

    database:
        image: postgres:17
        container_name: database
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h database || exit 1']
            timeout: 5s
            interval: 10s
            retries: 5
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        restart: always
        networks:
            - contributions_network

volumes:
    backend_node_modules:
        name: backend_node_modules
        driver: local
        driver_opts:
          type: none
          o: bind
          device: ${PWD}/node_modules

networks:
    contributions_network:
        driver: bridge