services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3010:3010'
        env_file:
            - .env
        restart: always

    database:
        image: postgres:17.2
        container_name: database
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U sm -d sm -h localhost || exit 1']
            timeout: 5s
            interval: 10s
            retries: 5
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=sm
            - POSTGRES_USER=sm
            - POSTGRES_PASSWORD=password
        restart: always

    metabase:
        image: metabase/metabase:latest
        container_name: metabase
        platform: linux/amd64
        healthcheck:
            test: curl --fail -I http://localhost:3000/api/health || exit 1
            interval: 15s
            timeout: 5s
            retries: 5
        volumes:
            - ./data/metabase:/dev/random:ro
        ports:
            - 3000:3000
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: sm
            MB_DB_PORT: 5432
            MB_DB_USER: sm
            MB_DB_PASS: password
            MB_DB_HOST: database
