services:
    backend:
        container_name: backend
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3010:3010'
        env_file:
            - .env
        restart: always

    database:
        image: postgres:17.2
        container_name: database
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U sm -d sm -h localhost || exit 1']
            timeout: 5s
            interval: 10s
            retries: 5
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=sm
            - POSTGRES_USER=sm
            - POSTGRES_PASSWORD=password
        restart: always